site_name: Documentação QuarkRH
site_description: Documentação técnica do projeto

theme:
  name: material
  custom_dir: docs/assets
  language: pt-BR

  logo: assets/img/logo.svg
  favicon: assets/img/logo.svg

  palette:
    scheme: default
    primary: '#3D3932'
    accent: '#EA8C0C'

  features:
    - navigation.tabs
    - navigation.expand
    - navigation.instant
    - content.code.annotate    
    - content.tabs.link      
    
  icon:
    repo: fontawesome/brands/github

nav:
  - Visão Geral: 'index.md'
  - Módulos: 
    - Departamento Pessoal: 
      - Dashboard: 'dashboard.md'
      - Colaborador: 
        - Gerenciar: 'dp/colaborador/gerenciar.md'
        - Ativar colaboradores em lote: 'dp/colaborador/ativar_lote.md'
        - Documentos em lote: 'dp/colaborador/documento_lote.md'
    - Frequencia: 'frequencia.md'
    - Férias: 'ferias.md'
    - Comunicação: 'comunicacao.md'
    - Saúde Ocupacional: 'so.md'
    - Benefícios: 'beneficios.md'
    - Gestao de EPI: 'epi.md'
    - Avaliação de Desempenho: 'avaliacao.md'
    - Perfil Comportamental: 'perfil.md'
    - Pesquisa de Clima: 'pesquisa.md'
    - Feedbacks: 'feedbacks.md'
    - Recrutamento e Seleção: 'res.md'
    - Portal do Gestor: 'gestor.md'
    - Portal do Colaborador: 'colaborador.md'
    - Assinatura Eletronica: 'sign.md'
    - Treinamento e Desenvolvimento: 'ted.md'

plugins:
  - search
  - macros
  - include-markdown

extra_css:
  - assets/css/default.css

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.keys
  - admonition
  - footnotes
  - attr_list